
--=============================================================================
-- Found the following lookup for Disposition Codes at:
--	https://www.lvmpd.com/home/showpublisheddocument/42/638298531765830000
/*
A ARRESTED
B CITATION ISSUED
C INCDT./CRIME REPORT (PRIMARY)
D INCDT./CRIME REPORT (PRIMARY) ARREST MADE
E INCDT./CRIME REPORT (PRIMARY) CITATION ISSUED
F UNFOUNDED
G DISPATCH CANCELLED
H GONE ON ARRIVAL
I UNABLE TO LOCATE
J SETTLED AT SCENE
K REPORT TAKEN-OTHER THAN INCDT./CRIME REPORT (DO NOT USE IF AN INCDT./CRIME REPORT WAS TAKEN)
L HANDLED BY OTHER JURISDICTION
M WARNING AND/OR SUBJECT ADVISED
O FALSE ALARM
P REFUSED TO SIGN COMPLAINT
Q HANDLED BY UNIT OTHER THAN PATROL (INDICATE SPECIFIC UNIT)
R RADIO BROADCAST ONLY
S NON-CRIMINAL DETAIL COMPLETE
T REPORT TAKEN UNDER PREVIOUS EVENT #
Z INSURANCE REPORT (CAD Event only)
*/
--=============================================================================

IF OBJECT_ID( 'LVMPD_Crime.dbo.lkpDispositionCodes' ) IS NOT NULL
	DROP TABLE LVMPD_Crime.dbo.lkpDispositionCodes
CREATE TABLE LVMPD_Crime.dbo.lkpDispositionCodes
(
	DispositionCode CHAR(1)
	, DispositionDescription VARCHAR(100)
)

INSERT INTO LVMPD_Crime.dbo.lkpDispositionCodes( DispositionCode, DispositionDescription )
VALUES( 'A', 'ARRESTED' )
, ( 'B', 'CITATION ISSUED' )
, ( 'C', 'INCDT./CRIME REPORT (PRIMARY)' )
, ( 'D', 'INCDT./CRIME REPORT (PRIMARY) ARREST MADE' )
, ( 'E', 'INCDT./CRIME REPORT (PRIMARY) CITATION ISSUED' )
, ( 'F', 'UNFOUNDED' )
, ( 'G', 'DISPATCH CANCELLED' )
, ( 'H', 'GONE ON ARRIVAL' )
, ( 'I', 'UNABLE TO LOCATE' )
, ( 'J', 'SETTLED AT SCENE' )
, ( 'K', 'REPORT TAKEN-OTHER THAN INCDT./CRIME REPORT (DO NOT USE IF AN INCDT./CRIME REPORT WAS TAKEN)' )
, ( 'L', 'HANDLED BY OTHER JURISDICTION' )
, ( 'M', 'WARNING AND/OR SUBJECT ADVISED' )
, ( 'N', 'No Disposition' )
, ( 'O', 'FALSE ALARM' )
, ( 'P', 'REFUSED TO SIGN COMPLAINT' )
, ( 'Q', 'HANDLED BY UNIT OTHER THAN PATROL (INDICATE SPECIFIC UNIT)' )
, ( 'R', 'RADIO BROADCAST ONLY' )
, ( 'S', 'NON-CRIMINAL DETAIL COMPLETE' )
, ( 'T', 'REPORT TAKEN UNDER PREVIOUS EVENT #' )
, ( 'Z', 'INSURANCE REPORT (CAD Event only)' )

CREATE UNIQUE CLUSTERED INDEX UC_IDX_DISP_CODE ON LVMPD_Crime.dbo.lkpDispositionCodes( DispositionCode )